apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloud-native-final
  name: cloud-native-final
  namespace: cn202103
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-native-final
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
      labels:
        app: cloud-native-final
    spec:
      containers:
      - image: harbor.edu.cn/cn202103/cloud-native-final:{VERSION}
        name: cloud-native-final
      imageFullSecrets:
        - name: cn202103
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-native-final
  namespace: cn202103
  labels:
    app: cloud-native-final
spec:
  type: NodePort
  selector:
    app: cloud-native-final
  ports:
  - name: tcp
    nodePort: 40000
    protocol: TCP
    port: 8998
    targetPort: 8998
